# Change these first
owner: manojvipl # Updated capitalization of the owner
repo: upptime # Updated capitalization of the repository

sites:
  - name: VIPL-Website
    url: https://varianceinfotech.com
  - name: CRMTiger-Website
    url: https://crmtiger.com
  - name: Demo-Website
    url: http://realtyshine.com
  - name: Saleshiker-Website
    url: https://saleshiker.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.varianceinfotech.com
  #baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Upptime/Upptime.js.org/master/static/img/icon.svg # Updated capitalization
  name: Upptime
  introTitle: "Monitor Server"
  introMessage: Monitor Server With 5 Minutes Interval For Up/Down Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/manojvipl/upptime # Updated capitalization of owner and repo

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
